#!/usr/bin/env bash

#enable colors for terminal window
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

#extra commands/aliases
alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias mkcl="$HOME/pr0gramming/goFast/insertClass/prog $2"
alias tbp='cd $HOME/Skool/Tau_Beta_Pi/TauBetaPi_CAAA_site/tbp'
alias bui='cd $HOME/pr0gramming/430/BossyUI'
#@@@ add gitit
#alias gitit='$HOME/pr0gramming/goFast/gitPullAddCommitPush/letsdothis.pl'

