#!/usr/bin/env bash

#enable colors for terminal window
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

#COWZ=/usr/local/Cellar/cowsay/3.04/share/cows
#sandz(){
#  CHOSEN_COW= $(basename ls $COWZ | head -$((RANDOM%$(ls | wc -w)+1)) | tail -1 .cow)
#  echo "Chosen cow: $CHOSEN_COW"
#  CHOSEN_COW= $(basename "$COWZ/$CHOSEN_COW .cow")
#  echo "Chosen cow: $CHOSEN_COW"
#  echo "Anakin Skywalker does not like sand" | cowsay -f CHOSEN_COW
#
#  echo $CHOSEN_COW
#}

#extra commands/aliases
alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias mkcl="$HOME/pr0gramming/goFast/insertClass/prog $2"
alias tbp='cd $HOME/Skool/Tau_Beta_Pi/TauBetaPi_CAAA_site/tbp'
alias bui='cd $HOME/pr0gramming/430/BossyUI'
alias sandy='npm run sandbox'
alias sand='echo "Anakin does not like sand" | cowsay -f dragon && npm run sandbox'
alias myro='cd /Users/DarkSide/pr0gramming/430/pairProg/attempt2/myronFucksCactii'
alias myron='cd /Users/DarkSide/pr0gramming/430/pairProg/attempt2/myronFucksCactii'
alias cramIt='cd /Users/DarkSide/pr0gramming/430/pairProg/cramIt/BossyUI'
alias cramShit='cd /Users/DarkSide/pr0gramming/430/new_side/student-site'
alias update='brew update'
alias e499='cd $HOME/Skool/EECE_499'
alias pac='python pacman.py -p ANNAgent'
alias nog='python pacman.py -p ANNAgent -l mediumClassicNoGhosts'
alias nogf='python pacman.py -p ANNAgent -l mediumClassicNoGhosts --frameTime 0'
alias nogfnd='python pacman.py -p ANNAgent -l mediumClassicNoGhosts --frameTime 0 -q'
alias pacf='python pacman.py --frameTime 0 -p ANNAgent'
#@@@ add gitit
#alias gitit='$HOME/pr0gramming/goFast/gitPullAddCommitPush/letsdothis.pl'
# Jake Hansen's thing to display git branch in terminal
# display git branch while in repo
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\u@\h \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "


export PATH=$PATH:$HOME/Skool/Senior_Project/RiscV/riscv/bin
export RISCV=$HOME/Skool/Senior_Project/RiscV/riscv

