#!/usr/env bash

#allow use of word "open" to open file in window manager, nemo rather than typing nemo
alias open='nemo'
alias ise='/opt/Xilinx/14.7/ISE_DS/ISE/bin/lin64/ise'
alias proj='cd $HOME/Documents/490A/'


# Jake Hansen's thing to display git branch in terminal
# display git branch while in repo
parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}
export PS1="\u@\h \[\033[32m\]\w\[\033[33m\]\$(parse_git_branch)\[\033[00m\] $ "

